# Generated by Django 5.1.5 on 2025-01-30 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish')], max_length=2)),
                ('key_type', models.CharField(choices=[('TPL', 'Template'), ('INI', 'Initialize')], max_length=3)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_lms.site')),
            ],
            options={
                'unique_together': {('site', 'key', 'language')},
            },
        ),
    ]
